nome_e_idade = input().split()
nome, sobrenome, idade = nome_e_idade[0], nome_e_idade[1], int(nome_e_idade[2])
produto = input()
valor_e_desconto = input().split()
valor, desconto = int(valor_e_desconto[0]), float(valor_e_desconto[1])
Valor_Descontado = valor * (1 - desconto)
print('Olá, {} {}!!!\n'.format(nome, sobrenome))
print('Feliz aniversário!!\n')
print('Estamos muito felizes por te presentear em seu aniversário de {} anos.'.format(idade + 1), end='\n')
print('Por isso estamos enviando para você uma super promoção o(a) {}'.format(produto.upper()), end='\n')
print('que custa R$ {:.1f}, mas como é seu aniversário, estamos te dando de presente'.format(valor), end='\n')
print('{:.0f}% de desconto e o seu produto sairá por R$ {}.'.format(desconto * 100, Valor_Descontado))
print('\nVem aproveitar!!')
